# Generated by Django 4.1.3 on 2022-11-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('Seleccione', 'Seleccione'), ('Recibido', 'Recibido'), ('No Recibido', 'No recibido')], default='S', max_length=20),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
