# Generated by Django 4.1.3 on 2022-11-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_correspondencia_estado_alter_residencia_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='id',
        ),
        migrations.AlterField(
            model_name='residencia',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
